# Generated by Django 5.0.7 on 2024-07-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='profileimage/')),
                ('personalsummary', models.CharField(max_length=500)),
                ('featuredskills', models.ImageField(upload_to='skillicon/')),
            ],
        ),
    ]
