# Generated by Django 5.0.7 on 2024-07-14 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_subsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='subsection',
            name='featuredskills',
            field=models.ImageField(blank=True, null=True, upload_to='skillicon/'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profileimage/'),
        ),
        migrations.CreateModel(
            name='portfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='CV.portfolio')),
            ],
        ),
    ]
