# Generated by Django 5.0.7 on 2024-07-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0003_portfolio_alter_subsection_featuredskills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(upload_to='Portfolio/sampleimages'),
        ),
    ]
